---
title: 'Dennis Iversens CV '
subject: Dennis Iversens CV
author:
- Dennis Bæk Iversen
keywords: dennis iversen, cv, job, programmør
rights: Creative Commons Non-Commercial Share Alike 3.0
language: da-DK
cover-image: "images/cover.png"
lang: da
date: '2015-01-27'
format-arguments:
    pdf: -S --number-sections 
    html: -S --template=templates/default.html --toc-depth=3 --chapters --number-sections --toc
    epub: -S --epub-chapter-level=3 --number-sections --toc 
    mobi: ok
ignore-files: 
- README.md

...

